pull_request_rules:
  - name: label Dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      label:
        add:
          - dependabot

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:

  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
