version: "3"

dotenv:
  - .env
  - "{{.ENV}}/.env."
  - "{{.HOME}}/.env"

tasks:
  build:
    desc: Build the application
    cmds:
      - npm run build

  deploy:files:
    desc: Copy necessary files to server
    cmds:
      - rsync -avz --exclude 'node_modules' --exclude '.git' src/ dist/ package*.json deploy.sh .env tsconfig.json {{.DEPLOY_SERVER_USER}}@{{.DEPLOY_SERVER_HOST}}:{{.DEPLOY_PATH}}

  deploy:install:
    desc: Install dependencies on server
    cmds:
      - ssh {{.DEPLOY_SERVER_USER}}@{{.DEPLOY_SERVER_HOST}} "cd {{.DEPLOY_PATH}} && npm install --omit=dev"
      - ssh {{.DEPLOY_SERVER_USER}}@{{.DEPLOY_SERVER_HOST}} "cd {{.DEPLOY_PATH}} && chmod +x deploy.sh"

  deploy:restart:
    desc: Restart the application
    cmds:
      - ssh {{.DEPLOY_SERVER_USER}}@{{.DEPLOY_SERVER_HOST}} "cd {{.DEPLOY_PATH}} && pm2 delete discord-bot || true"
      - ssh {{.DEPLOY_SERVER_USER}}@{{.DEPLOY_SERVER_HOST}} "cd {{.DEPLOY_PATH}} && ./deploy.sh"

  deploy:
    desc: Deploy the application
    deps: [build]
    cmds:
      - task: deploy:files
      - task: deploy:install
      - task: deploy:restart
